spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: pipeline-api
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pipeline?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: app
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
    locations: classpath:db/migration
server:
  port: 8080

# CORS: Next.js(예: http://localhost:3000)에서 호출
app:
  cors:
    allow-origins: "http://localhost:3000"
  storage:
    base-dir: uploads
    pdb-dir: pdb
